import{a as g,S as b,i}from"./assets/vendor-Dy2ZTtfi.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L="50828766-d4c68cffebe8589d5ede8282a",w="https://pixabay.com/api/",v=15;async function S(r,n=1){const t={key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:n};try{return(await g.get(w,{params:t})).data}catch{throw new Error("Failed to fetch images")}}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function P(r){const n=r.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",n),q.refresh()}function B(){u.innerHTML=""}function E(){f.classList.add("visible")}function M(){f.classList.remove("visible")}function $(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}const h=document.querySelector(".form"),O=h.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let l="",s=1,d=0;h.addEventListener("submit",async r=>{if(r.preventDefault(),l=O.value.trim(),s=1,B(),p(),!l){i.warning({message:"Please enter a search term."});return}await y()});x.addEventListener("click",async()=>{s++,await y()});async function y(){E();try{const r=await S(l,s),{hits:n,totalHits:t}=r;if(n.length===0&&s===1){i.error({message:"No images found. Please try another search."});return}P(n),d=Math.ceil(t/15),s<d?$():(p(),i.info({message:"We're sorry, but you've reached the end of search results."})),s>1&&A()}catch(r){i.error({message:"Something went wrong. Try again later."}),console.error(r)}finally{M()}}function A(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
