import{a as v,S,i as a}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const q="50828766-d4c68cffebe8589d5ede8282a",P="https://pixabay.com/api/",M=15;async function f(o,t=1){const e={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:t};try{return(await v.get(P,{params:e})).data}catch{throw new Error("Failed to fetch images")}}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){m.innerHTML=""}function g(){h.classList.add("visible")}function b(){h.classList.remove("visible")}function L(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const w=document.querySelector(".form"),$=w.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let c="",i=1,u=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),c=$.value.trim(),i=1,E(),l(),!c){a.warning({message:"Please enter a search term."});return}g();try{const t=await f(c,i),{hits:e,totalHits:n}=t;if(e.length===0){a.error({message:"No images found. Please try another search."});return}p(e),u=Math.ceil(n/15),i<u?L():(l(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(t){a.error({message:"Something went wrong. Try again later."}),console.error(t)}finally{b()}});O.addEventListener("click",async()=>{l(),g();try{i++;const o=await f(c,i),{hits:t,totalHits:e}=o;p(t),i<Math.ceil(e/15)?L():(l(),a.info({message:"We're sorry, but you've reached the end of search results."})),x()}catch(o){a.error({message:"Something went wrong. Try again later."}),console.error(o)}finally{b()}});function x(){const o=document.querySelector(".gallery-item");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
